version: 2
updates:
  # Configure updates for Conda environment files (environment.yml)
  - package-ecosystem: "conda"
    directory: "/" # Path to the directory containing environment.yml
    schedule:
      interval: "weekly" # Check for updates weekly (can also be 'daily' or 'monthly')
    open-pull-requests-limit: 0
